version: '3.8'

services:
  frontend:
    container_name: frontend
    build:
      context: ./app/client/
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "5173:8080"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: always
  backend: 
    build:
      context: ./app/backend/
      dockerfile: Dockerfile
    image: backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    restart: always


  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: PingPong
#    networks:
#      - freecodecamp
    restart: always

  # ? need volume  also for envs of course for testing
  # ! put envs in .env file and should be ignord by git
#  pg-admin:
#    image: dpage/pgadmin4
#    ports:
#      - "5050:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: name@example.com
#      PGADMIN_DEFAULT_PASSWORD: admin

#networks:
#  freecodecamp: