version: '3.8'



volumes:
  frontend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/dist
#  db_data:
#    driver: local
#    driver_opts:
#      type: none
#      o: bind
#      device: /home/ael-mous/data/mysql

services:
  # frontend:
  #   container_name: frontend
  #   build:
  #     context: ./app/client/
  #     dockerfile: Dockerfile
  #   image: frontend
  #   restart: unless-stopped
  #   depends_on:
  #     - backend
    

  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ./app/nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - frontend
  #   restart: unless-stopped

  # backend: 
  #   build:
  #     context: ./app/backend/
  #     dockerfile: Dockerfile
  #   image: backend
  #   ports:
  #     - "3000:3000"
  #     - "1212:1212"
  #     - "4000:4000"
  #     - "4343:4343"
  #   depends_on:
  #     - postgres
  #   restart: always

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: PingPong
#    networks:
#      - freecodecamp
    restart: always

  # ? need volume  also for envs of course for testing
  # ! put envs in .env file and should be ignord by git
  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: name@example.com
      PGADMIN_DEFAULT_PASSWORD: admin

# networks:
#  freecodecamp: