version: '3.8'



volumes:
  pg_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /tmp/db1


services:
  frontend:
    container_name: frontend
    build:
      context: ./app/client/
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "5173:5173"
    restart: unless-stopped
    depends_on:
      - backend
    
  backend: 
    build:
      context: ./app/backend/
      dockerfile: Dockerfile
    image: backend
    ports:
      - "3000:3000"
      - "1212:1212"
      - "4000:4000"
      - "4343:4343"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_volume:/var/lib/postgresql/data
    restart: always

  # ? need volume  also for envs of course for testing
  # ! put envs in .env file and should be ignord by git
  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env

# networks:
#  freecodecamp: