version: '3.8'

networks:
  net:

services:
  frontend:
    container_name: frontend
    build:
      context: ./app/client/
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "5173:5173"
    networks:
      - net
    restart: unless-stopped
    depends_on:
      - backend
    
  backend: 
    build:
      context: ./app/backend/
      dockerfile: Dockerfile
    image: backend
    ports:
      - "3000:3000"
      - "1212:1212"
      - "4000:4000"
      - "4343:4343"
    networks:
      - net
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - net
    restart: always

  # ? need volume  also for envs of course for testing
  # ! put envs in .env file and should be ignord by git
  pg-admin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    env_file:
      - .env

# networks:
#  freecodecamp: